StylesPath = styles
MinAlertLevel = warning
Packages = Google, proselint, write-good

[*]
BasedOnStyles = Vale, Google, proselint, write-good

# Custom repository overrides to disable overly pedantic rules
Google.Headings = NO
Google.WordList = NO
write-good.E-Prime = NO
